---
# handlers file for post-install
- name: Restart service on centos
  service:
    name: chrony
    state: restarted
    enabled: yes
  when:
    ansible_distribution == "CentOS"

- name: Restart service on ubuntu
  service:
    name: ntp
    state: restarted
    enabled: yes
  when:
    ansible_distribution == "Ubuntu"
ubuntu@ip-172-31-82-97:~/vprofile/roles/post-install$ cat tasks/main.yml 
#SPDX-License-Identifier: MIT-0
---
# tasks file for post-install
- name: Install ntp agent on centos
  yum:
    name: "{{item}}"
    state: present
  when:
    ansible_distribution == "CentOS"
  loop:
    - chrony
    - wget
    - zip
    - unzip
    - git

- name: Insatll ntp agent on Ubuntu
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  when:
    ansible_distribution == "Ubuntu"
  loop:
    - ntp
    - wget
    - zip
    - unzip
    - git

- name: Start service on centos
  service:
    name: chrony
    state: started
    enabled: yes
  when:
    ansible_distribution == "CentOS"

- name: Start service on ubuntu
  service:
    name: ntp
    state: started
    enabled: yes
  when:
    ansible_distribution == "Ubuntu"

- name: Banner file
  copy:
    content: '#This server is managed by ansible. No manual changes please.'
    dest: /etc/motd

- name: Create a folder
  file:
    path: "{{mydir}}"
    state: directory

- name: Deploy ntp agent conf on centos
  template:
    src: ntpconf_centos,j2
    dest: /etc/chrony.conf
    backup: yes
  when: ansible_distribution == "CentOS"
  notify:
    - Restart service on centos

- name: Deploy ntp agent conf on ubuntu
  template:
    src: ntpconf_ubuntu.j2
    dest: /etc/ntp.conf
    backup: yes
  when: ansible_distribution == "Ubuntu"
  notify:
    - Restart service on ubuntu

- name: Dump file
  copy:
    src: myfile.txt
    dest: /tmp/myfile.txt 