all:
  hosts:
    web01:
      ansible_host: 172.31.82.29
    web02:
      ansible_host: 172.31.82.184
    db01:
      ansible_host: 172.31.94.53

  children:
    webservers:
      hosts:
        web01:
        web02:
    dbservers:
      hosts:
        db01:
    dc_oregon:
      children:
        webservers:
        dbservers:
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: clientkey.pem
